# DEV
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
nameSuffix: -dev
labels:
- pairs:
    app: donotdrivenow-dev
  includeSelectors: true
images:
- name: kustomize-managed-image-name
  newName: ghcr.io/ayqazi/donotdrivenow
  newTag: stage
