apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      restartPolicy: Always
      volumes:
      - name: 'postgres-data'
        persistentVolumeClaim:
          claimName: 'postgres-data-claim'
      containers:
      - name: postgres
        image: 'postgres:16'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: '/srv/postgresql/data'
          name: 'postgres-data'
        env:
        - name: 'PGDATA'
          value: '/srv/postgresql/data'
        envFrom:
        - secretRef:
            name: 'postgres-setup'
