apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      restartPolicy: Always
      volumes:
      - name: 'minio-data'
        persistentVolumeClaim:
          claimName: 'minio-data-claim'
      containers:
      - name: minio
        image: 'quay.io/minio/minio:latest'
        imagePullPolicy: IfNotPresent
        args: [ 'server', '/data', '--address', ':9000', '--console-address', ':9001' ]
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: '/data'
          name: 'minio-data'
        env:
        - name: 'MINIO_ROOT_USER'
          value: 'admin'
        envFrom:
        - secretRef:
            name: 'minio-setup'
