apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  type: NodePort
  ports:
  - name: 'api'
    port: 9000
  - name: 'webui'
    port: 9001
  selector:
    app: minio
