# STAGE
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
nameSuffix: -stage
labels:
- includeSelectors: true
  pairs:
    app: donotdrivenow-stage
images:
- name: kustomize-managed-image-name
  newName: ghcr.io/ayqazi/donotdrivenow
  newTag: 0bae316d4a1598da78b46e444fb8ee0dfcef7ce0
