apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      restartPolicy: Always
      volumes:
      - name: 'mlflow-artifacts'
        persistentVolumeClaim:
          claimName: 'mlflow-artifacts-claim'
      containers:
      - name: mlflow
        image: 'ghcr.io/mlflow/mlflow:v2.13.0'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        command: [ '/bin/sh' ]
        volumeMounts:
        - mountPath: '/srv/mlflow/artifacts'
          name: 'mlflow-artifacts'
        args:
        - '-c'
        - "pip install --quiet psycopg2-binary &&
          mlflow ui --host 0.0.0.0 --port 5000 --workers 1
          --backend-store-uri '$(BACKEND_STORE_URI)'
          --serve-artifacts
          --default-artifact-root mlflow-artifacts:/
          --artifacts-destination /srv/mlflow/artifacts"
        envFrom:
        - secretRef:
            name: mlflow
