apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: 'ghcr.io/mlflow/mlflow:v2.13.0'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        command: [ '/bin/sh' ]
        args: [ '-c', "pip install --quiet psycopg2-binary && mlflow ui --host 0.0.0.0 --port 5000 --workers 1 --backend-store-uri '$(BACKEND_STORE_URI)'" ]
        envFrom:
        - secretRef:
            name: mlflow
