apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'donotdrivenow'
spec:
  selector:
    matchLabels:
      app: 'donotdrivenow'
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: 'donotdrivenow'
    spec:
      containers:
        - name: 'donotdrivenow'
          image: 'kustomize-managed-image-name'
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: 'secure-donotdrivenow'
