apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
images:
- name: kustomize-managed-image-name
  newName: ghcr.io/ayqazi/donotdrivenow
  newTag: c490c38c72d33475fd23490af72431b7716e4fba
